version: "3.9"
services:
  mongodb:
    image : mongo
    container_name: "mongodb"
    environment:
        - MONGO_INITDB_DATABASE=RecipeTracker
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
        - "27017:27017"
    volumes:
        - ./mongodb_data_container:/data/db
