name: Deploy to Dev Environment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build, Push, and Deploy to Heroku
      id: heroku
      uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        docker_compose_file: './docker-compose.yml'
        heroku_apps: '[{"imagename":"recipe-tracker-api","appname":"recipe-tracker-staging","apptype":"web"}]'
